name: Push
on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

env:
  FILENAME: AcrossProjectDistribution
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Gradle Build
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 4.8.1
        arguments: clean buildZip -DmavenCredUserName=${{ secrets.NAME }} -DmavenCredPassword=${{ secrets.GITHUB_TOKEN }} -DmavenRepoUrl=http://maven.aliyun.com/nexus/content/groups/public/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILENAME }}.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/distributions/${{ env.FILENAME }}.zip
